In [14]:
import numpy as np

In [15]:
import pandas as pd

In [16]:
#tensors..........

In [19]:
#0D TENSOR
a = np.array(4)

In [20]:
a

array(4)

In [21]:
a.ndim

0

In [23]:
#1 D tensor
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [24]:
a.ndim

1

In [27]:
#2D tensor
b=np.array([[1,1,2],[3,8,0],[9,4,8]])

In [28]:
b

array([[1, 1, 2],
       [3, 8, 0],
       [9, 4, 8]])

In [29]:
b.ndim

2

In [31]:
#data gathering

In [32]:
#-------- CSV

In [33]:
import pandas as pd

In [34]:
import seaborn as sns

In [40]:
t= sns.load_dataset('titanic')

In [43]:
t.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [49]:
import seaborn as sns

df = sns.load_dataset("titanic")
df = df[["sex", "age", "class", "alive"]]

In [50]:
df

        sex   age   class alive
0      male  22.0   Third    no
1    female  38.0   First   yes
2    female  26.0   Third   yes
3    female  35.0   First   yes
4      male  35.0   Third    no
..      ...   ...     ...   ...
886    male  27.0  Second    no
887  female  19.0   First   yes
888  female   NaN   Third    no
889    male  26.0   First   yes
890    male  32.0   Third    no

[891 rows x 4 columns]

In [1]:
import pandas as pd
import requests

In [3]:
response = requests.get('https://api.themoviedb.org/3/movie/popular?api_key=54499596e7c331abdc16e3f1acd4fca9')

In [4]:
response

In [7]:
response.json()['results']

[{'adult': False,
  'backdrop_path': '/b0LviwKbDto7Qq0D4DzGoVHpF4C.jpg',
  'genre_ids': [878, 28, 12],
  'id': 969681,
  'title': 'Spider-Man: Brand New Day',
  'original_language': 'en',
  'original_title': 'Spider-Man: Brand New Day',
  'overview': "Fighting crime full-time as Spider-Man in a world that doesn't remember him—and the pressure of seeing his old friends move on without him—sparks a change in Peter Parker he may not have the power to control. But that transformation might also be the only thing that can stop a shocking new threat to the city and those he loves - a powerful villain no one can even see.",
  'popularity': 1946.0445,
  'poster_path': '/iPOn6DinuVyLY17YM9mKuPofV08.jpg',
  'release_date': '2026-07-28',
  'softcore': False,
  'video': False,
  'vote_average': 8.0,
  'vote_count': 782},
 {'adult': False,
  'backdrop_path': '/sSIzzVhhLfgLKVBcAUv0X6cLYz9.jpg',
  'genre_ids': [12, 28, 14],
  'id': 1368337,
  'title': 'The Odyssey',
  'original_language': 'en',
  'original_title': 'The Odyssey',
  'overview': 'Odysseus, the legendary King of Ithaca, embarks on a long and perilous journey home following the Trojan War. Throughout his voyage, he is forced to confront the whims of gods, mythological monsters, and trials that stretch both his cunning and his humanity to the breaking point.',
  'popularity': 1207.1844,
  'poster_path': '/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg',
  'release_date': '2026-07-15',
  'softcore': False,
  'video': False,
  'vote_average': 7.952,
  'vote_count': 2120},
 {'adult': False,
  'backdrop_path': '/4X2YSe8PaYbsBqX3TDmmIU4vOju.jpg',
  'genre_ids': [28, 12, 878],
  'id': 1081003,
  'title': 'Supergirl',
  'original_language': 'en',
  'original_title': 'Supergirl',
  'overview': 'When an unexpected and ruthless adversary strikes too close to home, Kara Zor-El, aka Supergirl, reluctantly joins forces with an unlikely companion on an epic, interstellar journey of vengeance and justice.',
  'popularity': 583.7759,
  'poster_path': '/1QCWdqzTfh2x9UylVpspIU6QTuM.jpg',
  'release_date': '2026-06-24',
  'softcore': False,
  'video': False,
  'vote_average': 6.74,
  'vote_count': 1462},
 {'adult': False,
  'backdrop_path': '/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg',
  'genre_ids': [28, 12, 878],
  'id': 634649,
  'title': 'Spider-Man: No Way Home',
  'original_language': 'en',
  'original_title': 'Spider-Man: No Way Home',
  'overview': 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
  'popularity': 438.4757,
  'poster_path': '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
  'release_date': '2021-12-15',
  'softcore': False,
  'video': False,
  'vote_average': 7.935,
  'vote_count': 22434},
 {'adult': False,
  'backdrop_path': '/yQIdU11DYQQp0neGtGtGxbGfRer.jpg',
  'genre_ids': [28, 14, 878],
  'id': 454639,
  'title': 'Masters of the Universe',
  'original_language': 'en',
  'original_title': 'Masters of the Universe',
  'overview': 'After being separated for 15 years, the Sword of Power leads Prince Adam back to Eternia, where he discovers his home shattered under the fiendish rule of Skeletor. To save his family and his world, Adam must join forces with his closest allies, Teela and Duncan/Man-At-Arms, and embrace his true destiny as He-Man — the most powerful man in the universe.',
  'popularity': 431.6507,
  'poster_path': '/oRuyGUHdoaQxWP3SDfafGkStxTC.jpg',
  'release_date': '2026-06-03',
  'softcore': False,
  'video': False,
  'vote_average': 7.274,
  'vote_count': 1517},
 {'adult': False,
  'backdrop_path': '/flxau5Iu7bChQHsESqvGZ3FQRaI.jpg',
  'genre_ids': [878, 53],
  'id': 1275779,
  'title': 'Disclosure Day',
  'original_language': 'en',
  'original_title': 'Disclosure Day',
  'overview': "A cybersecurity expert becomes a whistleblower after uncovering secrets about aliens, putting him on the run from a corporation. Meanwhile, a meteorologist experiencing strange phenomena joins forces with him to prove there's life beyond our understanding.",
  'popularity': 423.0327,
  'poster_path': '/AnJ8IQJI23hNpYXVNaythu061Ru.jpg',
  'release_date': '2026-06-10',
  'softcore': False,
  'video': False,
  'vote_average': 7.413,
  'vote_count': 2284},
 {'adult': False,
  'backdrop_path': '/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg',
  'genre_ids': [27, 53],
  'id': 1339713,
  'title': 'Obsession',
  'original_language': 'en',
  'original_title': 'Obsession',
  'overview': 'After breaking the mysterious "One Wish Willow" to win his crush\'s heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.',
  'popularity': 386.1505,
  'poster_path': '/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg',
  'release_date': '2026-05-13',
  'softcore': False,
  'video': False,
  'vote_average': 8.249,
  'vote_count': 4154},
 {'adult': False,
  'backdrop_path': '/lh3BDkmWJh998n4fQcHYcVi7dpm.jpg',
  'genre_ids': [12, 18, 28],
  'id': 1284465,
  'title': 'The Death of Robin Hood',
  'original_language': 'en',
  'original_title': 'The Death of Robin Hood',
  'overview': 'Grappling with his past after a life of crime and murder, Robin Hood finds himself gravely injured after a battle he thought would be his last. In the hands of a mysterious woman, he is offered a chance at salvation.',
  'popularity': 356.8336,
  'poster_path': '/92Tsfx7SFafOqWsotvrlJbHyehd.jpg',
  'release_date': '2026-06-18',
  'softcore': False,
  'video': False,
  'vote_average': 6.513,
  'vote_count': 149},
 {'adult': False,
  'backdrop_path': '/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg',
  'genre_ids': [10751, 14, 35, 12],
  'id': 1108427,
  'title': 'Moana',
  'original_language': 'en',
  'original_title': 'Moana',
  'overview': "Teenage Moana answers the Ocean's call and, for the first time, voyages beyond the reef of her island of Motunui with infamous demigod Maui on an unforgettable journey to restore prosperity to her people.",
  'popularity': 335.0097,
  'poster_path': '/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg',
  'release_date': '2026-07-08',
  'softcore': False,
  'video': False,
  'vote_average': 5.8,
  'vote_count': 163},
 {'adult': False,
  'backdrop_path': '/8sSKdEmlmqF4kJUd28SqthXC4yZ.jpg',
  'genre_ids': [16, 10751, 35, 12],
  'id': 1084244,
  'title': 'Toy Story 5',
  'original_language': 'en',
  'original_title': 'Toy Story 5',
  'overview': "When Bonnie receives a Lilypad tablet as a gift and becomes obsessed, Buzz, Woody, Jessie and the rest of the gang's jobs become exponentially harder when they have to go head to head with the all-new threat to playtime.",
  'popularity': 326.0148,
  'poster_path': '/sfQtVlIHljToOwYjhe21KPGzZWK.jpg',
  'release_date': '2026-06-17',
  'softcore': False,
  'video': False,
  'vote_average': 7.414,
  'vote_count': 746},
 {'adult': False,
  'backdrop_path': '/se8LfmZYFiNerF6U7zMUKePV0vE.jpg',
  'genre_ids': [27, 53],
  'id': 1481343,
  'title': "The Devil's Mouth",
  'original_language': 'en',
  'original_title': "The Devil's Mouth",
  'overview': "A group of college friends' Thailand adventure turns deadly when they become trapped in submerged caves with a dangerous predator. As oxygen runs low, past conflicts emerge in their desperate fight for survival.",
  'popularity': 298.2974,
  'poster_path': '/lH8k9uCWYn2b2gsYleqYBDPbWa8.jpg',
  'release_date': '2026-07-29',
  'softcore': False,
  'video': False,
  'vote_average': 6.671,
  'vote_count': 378},
 {'adult': False,
  'backdrop_path': '/kkcwhgSFd81QDlXo8ytrpHPQjhy.jpg',
  'genre_ids': [12, 16, 35, 10751, 14],
  'id': 1315772,
  'title': 'Minions & Monsters',
  'original_language': 'en',
  'original_title': 'Minions & Monsters',
  'overview': 'This is the rambunctious, ridiculous and totally true story of how the Minions conquered Hollywood, became movie stars, lost everything, unleashed monsters onto the world and then banded together to try and save the planet from the mayhem they had just created.',
  'popularity': 287.1336,
  'poster_path': '/nz7i42yhLIJ4ve9JKgM6NthoLHO.jpg',
  'release_date': '2026-06-24',
  'softcore': False,
  'video': False,
  'vote_average': 6.4,
  'vote_count': 253},
 {'adult': False,
  'backdrop_path': '/p7MklBlRr0eRAxJSOnuV4rO08z4.jpg',
  'genre_ids': [16, 28, 12, 14],
  'id': 980431,
  'title': 'Avatar Aang: The Last Airbender',
  'original_language': 'en',
  'original_title': 'Avatar Aang: The Last Airbender',
  'overview': "Avatar Aang, the world's last Airbender, learns of an ancient power that could save his culture from extinction. With the help of his friends, he embarks on a global quest to find it before it falls into the wrong hands and threatens to upend the peace they sacrificed everything to achieve.",
  'popularity': 283.6008,
  'poster_path': '/3sgnSfNT27Bx5O5ukr7B26mhEQq.jpg',
  'release_date': '2026-07-24',
  'softcore': False,
  'video': False,
  'vote_average': 9.3,
  'vote_count': 622},
 {'adult': False,
  'backdrop_path': '/wjwMC7u3xWKkrronolBqsIy4L0L.jpg',
  'genre_ids': [27, 9648, 878],
  'id': 1083381,
  'title': 'Backrooms',
  'original_language': 'en',
  'original_title': 'Backrooms',
  'overview': 'A strange doorway appears in the basement of a furniture showroom.',
  'popularity': 277.5393,
  'poster_path': '/rhGx6E3qRNMgj3i5su2oukNHwIQ.jpg',
  'release_date': '2026-05-27',
  'softcore': False,
  'video': False,
  'vote_average': 7.087,
  'vote_count': 2453},
 {'adult': False,
  'backdrop_path': '/jDvxsBemt2Iyslg7qn2WMzgxz23.jpg',
  'genre_ids': [28, 27, 878],
  'id': 1375646,
  'title': 'Colony',
  'original_language': 'ko',
  'original_title': '군체',
  'overview': 'Professor Se-jeong is thrust into a bloody nightmare when a rapidly mutating virus is released during a biotech conference causing authorities to seal the facility. Trapped inside with no escape, Se-jeong along with a small group of survivors must fight to stay alive while the infected undergo horrific transformations.',
  'popularity': 233.4194,
  'poster_path': '/tN799oUR0f1gUKDYdMNrDaY7I51.jpg',
  'release_date': '2026-05-21',
  'softcore': False,
  'video': False,
  'vote_average': 8.076,
  'vote_count': 381},
 {'adult': False,
  'backdrop_path': '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
  'genre_ids': [16, 28, 14],
  'id': 1311031,
  'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
  'original_language': 'ja',
  'original_title': '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
  'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
  'popularity': 205.3076,
  'poster_path': '/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
  'release_date': '2025-07-18',
  'softcore': False,
  'video': False,
  'vote_average': 8.583,
  'vote_count': 1562},
 {'adult': False,
  'backdrop_path': '/rOIaKlAX0SeNC25dFbM0y1mFsH6.jpg',
  'genre_ids': [12, 14, 28],
  'id': 1698863,
  'title': 'The Odyssey',
  'original_language': 'en',
  'original_title': 'The Odyssey',
  'overview': 'Based on the Ancient Greek epic. After ten years of war, King Odysseus sets sail for Ithaca, eager to reunite with his beloved. But his journey home is far more treacherous than the battlefield, as he must face deadly monsters and vengeful gods to survive.',
  'popularity': 199.2139,
  'poster_path': '/xBHCRB7zLIW41w8QskfwJhm32YF.jpg',
  'release_date': '2026-07-03',
  'softcore': False,
  'video': False,
  'vote_average': 5.143,
  'vote_count': 7},
 {'adult': False,
  'backdrop_path': '/7y8zWGEjs7tresw4Hzkkf4TdkcL.jpg',
  'genre_ids': [27, 10749],
  'id': 1564614,
  'title': 'Leviticus',
  'original_language': 'en',
  'original_title': 'Leviticus',
  'overview': 'Two teenage boys must escape a violent entity that takes the form of the person they desire most — each other.',
  'popularity': 196.1728,
  'poster_path': '/gnAsZvBygplNpp8PtjoTEYv3VPB.jpg',
  'release_date': '2026-06-17',
  'softcore': False,
  'video': False,
  'vote_average': 6.2,
  'vote_count': 95},
 {'adult': False,
  'backdrop_path': '/xWBiXclrRmTggQHMRsIn84YHavs.jpg',
  'genre_ids': [35],
  'id': 1273221,
  'title': 'Scary Movie',
  'original_language': 'en',
  'original_title': 'Scary Movie',
  'overview': "Twenty-six years after outrunning a suspiciously familiar masked killer, the Core Four are back in the killer's crosshairs and no horror movie IP is safe.",
  'popularity': 191.8962,
  'poster_path': '/znHT8peERZRWG1ME3r0Db0EV8k8.jpg',
  'release_date': '2026-06-03',
  'softcore': False,
  'video': False,
  'vote_average': 6.499,
  'vote_count': 1407},
 {'adult': False,
  'backdrop_path': '/dk68ykaNd3HdrDJyPJqEGsgvag7.jpg',
  'genre_ids': [28, 53, 80],
  'id': 1630409,
  'title': 'The Debt Collector',
  'original_language': 'th',
  'original_title': 'คนเดือดทวงแค้น',
  'overview': 'Tormented by past mistakes and a terminal diagnosis, an ex-debt collector returns to the underworld to protect the victims of a violent organization.',
  'popularity': 188.2742,
  'poster_path': '/qADBUb5ybrkRVGZEFF8Z4RuOwys.jpg',
  'release_date': '2026-07-20',
  'softcore': False,
  'video': False,
  'vote_average': 7.657,
  'vote_count': 51}]

In [21]:
tem_df= pd.DataFrame(response.json()['results'])[['id','title','overview','poster_path','release_date','video']]

In [22]:
df

,id,title,overview,poster_path,release_date,video
0,969681,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,/iPOn6DinuVyLY17YM9mKuPofV08.jpg,2026-07-28,False
1,1368337,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg,2026-07-15,False
2,1081003,Supergirl,When an unexpected and ruthless adversary stri...,/1QCWdqzTfh2x9UylVpspIU6QTuM.jpg,2026-06-24,False
3,634649,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg,2021-12-15,False
4,454639,Masters of the Universe,"After being separated for 15 years, the Sword ...",/oRuyGUHdoaQxWP3SDfafGkStxTC.jpg,2026-06-03,False
...,...,...,...,...,...,...
8555,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg,2025-07-18,False
8556,1698863,The Odyssey,Based on the Ancient Greek epic. After ten yea...,/xBHCRB7zLIW41w8QskfwJhm32YF.jpg,2026-07-03,False
8557,1564614,Leviticus,Two teenage boys must escape a violent entity ...,/gnAsZvBygplNpp8PtjoTEYv3VPB.jpg,2026-06-17,False
8558,1273221,Scary Movie,Twenty-six years after outrunning a suspicious...,/znHT8peERZRWG1ME3r0Db0EV8k8.jpg,2026-06-03,False
8559,1630409,The Debt Collector,Tormented by past mistakes and a terminal diag...,/qADBUb5ybrkRVGZEFF8Z4RuOwys.jpg,2026-07-20,False

In [23]:
df = pd.DataFrame()

In [24]:
df

Empty DataFrame
Columns: []
Index: []

In [25]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/popular?api_key=54499596e7c331abdc16e3f1acd4fca9'.format(i))
    tem_df= pd.DataFrame(response.json()['results'])[['id','title','overview','poster_path','release_date','video']]
    df = pd.concat([df, tem_df], ignore_index=True)

In [28]:
df.shape

(8560, 6)

In [30]:
df.to_csv('movies.csv')

In [ ]:
#understanding data

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
import requests

In [ ]:
from bs4 import BeautifulSoup